apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        agentpool: system
      tolerations:
      - key: CriticalAddonsOnly
        effect: NoSchedule
        operator: Equal
        value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        agentpool: system
      tolerations:
      - key: CriticalAddonsOnly
        effect: NoSchedule
        operator: Equal
        value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        agentpool: system
      tolerations:
      - key: CriticalAddonsOnly
        effect: NoSchedule
        operator: Equal
        value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        agentpool: system
      tolerations:
      - key: CriticalAddonsOnly
        effect: NoSchedule
        operator: Equal
        value: "true"