apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rancher
    repoURL: https://github.com/liuzhiyong1982/cluster-baseline-settings
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
